# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
    # Install documentation requirements
    - requirements: docs/requirements.txt

    # Install the project itself (critical for AutoAPI)
    - method: pip
      path: .
